background #0d0d14
foreground #e7e7e7

cursor #e7e7e7
cursor_text_color #1D1C28

selection_foreground #e3e2e9
selection_background #292a2f

url_color #b2c5ff

# Normal colors
color0  #1D1C28
color1  #ac3231
color2  #2abf90
color3  #ebd99c
color4  #ac3231
color5  #92365e
color6  #009691
color7  #e7e7e7

# Bright colors
color8  #52263e
color9  #ac3231
color10 #2abf90
color11 #ebd99c
color12 #32355a
color13 #92365e
color14 #009691
color15 #e7e7e7
